### ISSUE TITLE
Please publish this package

### ISSUE THREAD

**Issue by maximletushov** [fluttercommunity/android_id#1]
Hi,

I guess this package was created since these issues took place:

https://github.com/fluttercommunity/plus_plugins/issues/824
https://github.com/fluttercommunity/plus_plugins/issues/954

Currently `android_id` package yet not available in [pub.dev](url). Please publish.

Waiting for release 🤞

**Comment by nohli** [comment]
@maximletushov thanks for opening this issue.

This plugin is published now 🙂 
https://pub.dev/packages/android_id
