### ISSUE TITLE
Add @visibleForTesting for AndroidId._methodChannel

### ISSUE THREAD

**Issue by AlexeyIWS** [fluttercommunity/android_id#17]
Now not opportunity for mock testing of the lib

**Comment by nohli** [comment]
@AlexeyIWS you can see how to mock a response in the [tests](https://github.com/fluttercommunity/android_id/blob/main/test/android_id_test.dart). Does that work for you?

**Comment by AlexeyIWS** [comment]
I think to be good that encapsulate channel name, for example:
https://github.com/fluttercommunity/plus_plugins/blob/main/packages/device_info_plus/device_info_plus_platform_interface/lib/method_channel/method_channel_device_info.dart
