### ISSUE TITLE
Issue with both android_id and gallery_saver

### ISSUE THREAD

**Issue by Chetan-3110** [fluttercommunity/android_id#3]
I am getting native issues while using this plugin with `gallery_saver`. While trying to save video in gallery, it downloads the video and just after it, app crashes. 
Here are the logs:

> E/AndroidRuntime(32333): FATAL EXCEPTION: DefaultDispatcher-worker-1
> E/AndroidRuntime(32333): Process: live.wowtalent.app, PID: 32333
> E/AndroidRuntime(32333): java.lang.IllegalAccessError: Illegal class access: 'g.a.b' attempting to access 'kotlinx.coroutines.H' (declaration of 'g.a.b' appears in /data/app/~~macQqWfUp_DZTOp0G3SyEw==/com.example.app-xXBmCCJr9Ho-V5qLMblw9w==/base.apk)
> E/AndroidRuntime(32333):        at g.a.b.invokeSuspend(GallerySaver.kt:5)
> E/AndroidRuntime(32333):        at q.n.i.a.a.resumeWith(ContinuationImpl.kt:4)
> E/AndroidRuntime(32333):        at kotlinx.coroutines.J.run(DispatchedTask.kt:18)
> E/AndroidRuntime(32333):        at android.os.Handler.handleCallback(Handler.java:938)
> E/AndroidRuntime(32333):        at android.os.Handler.dispatchMessage(Handler.java:99)
> E/AndroidRuntime(32333):        at android.os.Looper.loopOnce(Looper.java:201)
> E/AndroidRuntime(32333):        at android.os.Looper.loop(Looper.java:288)
> E/AndroidRuntime(32333):        at android.app.ActivityThread.main(ActivityThread.java:7870)
> E/AndroidRuntime(32333):        at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(32333):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> E/AndroidRuntime(32333):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by nohli** [comment]
How is the crash connected to this plugin?

Do you have a minimal reproducible code sample? 😊

And is [that issue](https://github.com/CarnegieTechnologies/gallery_saver/issues/184) related?

**Comment by Chetan-3110** [comment]
1. When I added this plugin, I got the mentioned crash in release mode while trying to save to gallery. Removing this plugin, fixed the issue. So, I am very certain about it.
2. I will share a minimal reproducible code sample in some time.
3. He is also facing the exact same issue but I am not sure if he is also using this plugin.

**Comment by nohli** [comment]
@Chetan-3110 could you try if [this](https://github.com/fluttercommunity/android_id/issues/5#issuecomment-1239062783) helps?

**Comment by nohli** [comment]
@Chetan-3110 is this still an issue for you?

Could you please try the latest version: `android_id: ^0.1.0`

Another user reported that deleting the `android` folder and recreating it via `flutter create .` fixed it.

**Comment by nohli** [comment]
Can you please try `android_id: ^0.2.0`
