### ISSUE TITLE
Add compatibility with AGP 8 (Android Gradle Plugin)

### ISSUE THREAD

**Issue by biklas7** [fluttercommunity/android_id#37]
Android Flutter plugins should add `namespace` under `android` inside the build configuration for the app.
Something like [this](https://github.com/fluttercommunity/plus_plugins/pull/1704/files).

Also check official android documentation [here](https://developer.android.com/build/publish-library/prep-lib-release#choose-namespace).

**Comment by biklas7** [comment]
Nice! Thanks 👍

**Comment by nohli** [comment]
Do you happen to know if the `namespace` is necessary for both `build.gradle` files, as done in the linked PR?

Because the (also linked) docs say
```
Starting with AGP 7.0, you can set the namespace in the app’s build.gradle file
```

**Comment by biklas7** [comment]
I think it's only needed for the app `build.gradle`.

**Comment by nohli** [comment]
Please check if version `0.3.0` works for you 🙏🏽

**Comment by biklas7** [comment]
Works great! Thanks 👍

**Comment by nohli** [comment]
@biklas7 thanks for the feedback. Could you please also check `0.3.1` (had to fix the `namespace` for [older AGP versions](https://github.com/fluttercommunity/android_id/issues/38))

**Comment by biklas7** [comment]
@nohli still working 👍
