### ISSUE TITLE
android_id package prevents apk from being output

### ISSUE THREAD

**Issue by acoutts** [fluttercommunity/android_id#4]
Not sure what it is but as soon as I added this package, running the `app:assemble${FLAVOR}Profile` task for my app would succeed without errors but never output an APK file. As soon as I removed this package, the APK is output again. Must be something odd with the build.gradle or manifest in this package that breaks apk output.

To clarify- the flutter build apk command does output the apk in the flutter-apk folder but the normal gradle build task does not put an apk. This is needed for integration tests: https://pub.dev/packages/integration_test#firebase-test-lab

**Comment by nohli** [comment]
Hi, thanks for writing this issue.

Could you please share a minimal, reproducible example, so I can test possible fixes?

**Comment by nohli** [comment]
@acoutts could you try if [this](https://github.com/fluttercommunity/android_id/issues/5#issuecomment-1239062783) helps?

**Comment by acoutts** [comment]
I am not going to do that because I have a lot of things setup in my android project like flavors and signing keys. There must be something wrong with the android configuration of the plugin which breaks the apk builds.

I downgraded to device_info_plus 3.2.4 to resolve it for now.

**Comment by nohli** [comment]
@acoutts these files are from the Flutter plugin template.

Which gradle version do you use in your project?

**Comment by acoutts** [comment]
Gradle plugin version: 7.2.2
Gradle version: 7.5.1

**Comment by nohli** [comment]
Ok thanks so much, I'll check the differencies between the plugins.
Any chance to test it locally with example code?

**Comment by nohli** [comment]
@acoutts is this still an issue for you?

Could you please try the latest version: `android_id: ^0.1.0`

And maybe upgrade the gradle dependencies.

**Comment by acoutts** [comment]
I've just tried on the latest version 0.1.3+1 and i've got the same issue still

**Comment by acoutts** [comment]
It's almost like a silent failure because the gradle command completes without any errors printed but the apk is never created..

**Comment by acoutts** [comment]
It's almost like a silent failure because the gradle command completes without any errors printed but the apk is never created..

I do not want to just delete my android folder because I have a lot of custom things like flavors, gradle files, manifests, etc.

**Comment by acoutts** [comment]
Looking deeper, the flutter build apk command usually outputs an apk in `outputs/apk`, but is not doing it either.

**Comment by acoutts** [comment]
Looking at the example app, if you try to build a profile apk with `flutter build apk --profile`, the example as it is fails with the following:

```

💪 Building with sound null safety 💪

Can't load Kernel binary: Invalid kernel binary format version.
Dart snapshot generator failed with exit code 254
Can't load Kernel binary: Invalid kernel binary format version.
Can't load Kernel binary: Invalid kernel binary format version.
Dart snapshot generator failed with exit code 254
Dart snapshot generator failed with exit code 254


FAILURE: Build failed with an exception.

* Where:
Script '/Users/andrew.coutts/Projects/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildProfile'.
> Process 'command '/Users/andrew.coutts/Projects/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Running Gradle task 'assembleProfile'...                         2,296ms
Gradle task assembleProfile failed with exit code 1
```

@nohli can you confirm if you get the same error? I wonder if this is related.

**Comment by acoutts** [comment]
I'm on the latest stable flutter (3.3.9)

**Comment by nohli** [comment]
Interesting investigation.
I can build the example app without any problems.

<img width="699" alt="Screenshot 2022-12-06 at 11 06 55" src="https://user-images.githubusercontent.com/43643339/205802706-03747d22-f7a3-4cd7-9ad3-f8a089a544d1.png">

<img width="512" alt="Screenshot 2022-12-06 at 11 07 06" src="https://user-images.githubusercontent.com/43643339/205802643-5205ffca-3a59-42b5-ba35-485d64b36c81.png">

Have you tried [clearing the cache?](https://stackoverflow.com/questions/56051502/cant-load-kernel-binary-invalid-kernel-binary-format-version-no-active-packag) Or are you using [fvm](https://github.com/fluttertools/fvm/issues/100)?

**Comment by acoutts** [comment]
We can close the issue here as I've concluded it must be a flutter issue. If i create a brand new flutter plugin and add it to my project I get the same behavior, so it's nothing unique to this plugin.
Weird one - I'll update this when I figure it out.

**Comment by nohli** [comment]
Ok thanks for the update.
Have you tried googling the issue (stupid question, I know)? Many people seem to have had it and there are several different reasons/fixes.

**Comment by acoutts** [comment]
Yea it's such a generic sounding problem it's difficult to search.
I found one person saying flutter-apk/ is the new location but I don't understand why specifically only my app doesn't output it to the apk/ location as well, and besides the integration_test package still references using the apk/ location.

**Comment by acoutts** [comment]
I do see they added the flutter-apk output here: https://github.com/flutter/flutter/pull/53718

I guess it's ok and i can just use the flutter-apk location, I just wonder about the "why" now and wanted to have closure on it.

**Comment by nohli** [comment]
Does your `flutter build apk` save the apk to `build/app/outputs/flutter-apk`?
And you expect it to also output to the other directory?

Given the [green output](https://user-images.githubusercontent.com/43643339/205802643-5205ffca-3a59-42b5-ba35-485d64b36c81.png) in terminal, the `flutter-apk` directory should be the right one?

**Comment by acoutts** [comment]
Update on this - I'm not sure exactly what fixed it but by deleting my android folder and re-creating it (along with my flavors, firebase setup, etc) -- it now works. That removed several files and I'm not sure exactly what fixed it yet, but if anyone else is stuck that's the right move - delete your android folder and do `flutter create` to re-create it, then set it back up how you had it before.
