### ISSUE TITLE
getId() method's behavior and handling of null returns

### ISSUE THREAD

**Issue by kra8** [fluttercommunity/android_id#45]
The getId() method, as per the documentation, returns a String?. I understand that this means it may potentially return a null value.

My questions are:

1. Under what circumstances will the getId() method return null?
2. What would be the best practice in handling a situation where null is returned?

Any guidance would be appreciated.

**Comment by nohli** [comment]
Hi kra!

Thanks for asking 😊

Normally, the value shouldn't be null.

Example causes for null or empty String are:
- Emulator
- First boot of device (id is not generated yet)
- No permissions granted for `Settings.Secure`
- Software issues
- Rooted phones with manipulated Android ID
- Users without user profile
- Unsigned apps

Regarding the best practice in handling null, it depends. May I know your use-case?
For example, if you need a unique identifier, you could generate your own random id and save it with shared preferences (which is often better than reading a device id - also note that it's not a device-wide value, as stated in the [docs](https://pub.dev/packages/android_id#important)).

**Comment by kra8** [comment]
Thank you for your response!

My use-case is to associate a unique identifier for each installed app with the logged-in user. So, in this case, it would be better to generate a own random ID rather than using the Android ID, correct?

**Comment by nohli** [comment]
I think, in your use-case it's better to generate the uuids yourself.

Using the Android ID could be seen as somewhat intrusive since it could allow cross-tracking of users across your apps. Furthermore, the API or rules for using the Android ID may change in the future, which would necessitate refactoring.

How about something like this?

```
class UniqueIdService {
  const UniqueIdService();

  static const String _uniqueIdKey_ = 'unique_id';

  /// Returns a unique id for this app.
  /// The id is persistent across app restarts.
  Future<String> getUniqueId() async {
    final storage = await SharedPreferences.getInstance();
    final savedId = storage.getString(_uniqueIdKey);

    // If id exists in local storage, return it.
    if (savedId != null) {
      return savedId;
    }

    // Else, generate a new id, save it in local storage, then return it.
    final newId = const Uuid().v4();
    await storage.setString(_uniqueIdKey, newId);
    return newId;
  }
}
```


```
  final uniqueId = await const UniqueIdService().getUniqueId();
```

You could also add the username to the key to save uuids of different users (as long as the username doesn't change).
There can also add a method for deleting the saved uuid (in case of a reset/logout).

**Comment by kra8** [comment]
Thank you for answering! I have decided to manage UUIDs myself!
