### ISSUE TITLE
`androidId` get result "Instance of 'Future<String?>'" 

### ISSUE THREAD

**Issue by blue492** [fluttercommunity/android_id#47]
Hi, when I execute the following code, the variable `androidId` get this result `Instance of 'Future<String?>'`
Why it happen?

```
 static Future<String> get_device_Id(BuildContext context) async {
     DeviceInfoPlugin deviceInfo = DeviceInfoPlugin();
     if (Theme.of(context).platform == TargetPlatform.iOS) {
       IosDeviceInfo iosDeviceInfo = await deviceInfo.iosInfo;
       return iosDeviceInfo.identifierForVendor.toString(); // unique ID on iOS
     } else {
       var _androidIdPlugin = AndroidId();
       return await _androidIdPlugin.getId().toString(); // unique ID on Android
     }
   }
```

**Comment by nohli** [comment]
Can I see the full method, please. Is it async?

**Comment by blue492** [comment]
> Can I see the full method, please. Is it async?

I updated the description

**Comment by nohli** [comment]
Are you awaiting for its result?

final id = await get_device_Id(context)?

If yes, do it like this:

const _androidIdPlugin = AndroidId();
final String? id = await _androidIdPlugin.getId();
       return id.toString(); // unique ID on Android

**Comment by blue492** [comment]
> Are you awaiting its result?
> 
> final id = await get_device_Id(context)?
> 
> If yes, do it like this:
> 
> final String? id = await AndroidId().getId(); return id.toString(); // unique ID on Android

Are you awaiting its result? Yes
But why? same method worked before

**Comment by nohli** [comment]
Do you see a difference between

  return await _androidIdPlugin.getId().toString()

and

  return (await _androidIdPlugin.getId()).toString()

**Comment by blue492** [comment]
> Do you see a difference between
> 
> return await _androidIdPlugin.getId().toString()
> 
> and
> 
> return (await _androidIdPlugin.getId()).toString()

`return (await _androidIdPlugin.getId()).toString()` solved the problem, thanks
