### ISSUE TITLE
Ids are not unique

### ISSUE THREAD

**Issue by telestia** [fluttercommunity/android_id#56]
I got same id on 2 different Android device, should I use fingerprint for unique deviceId?

DeviceId is: TP1A.220624.014

**Comment by nohli** [comment]
The string you provided is no Android ID:

https://distrowiki.miraheze.org/wiki/Android_13_build_TP1A.220624.014

How did you get it?

**Comment by telestia** [comment]
var deviceInfo = DeviceInfoPlugin();
  if (Platform.isAndroid) {
    AndroidDeviceInfo androidInfo = await deviceInfo.androidInfo;
    deviceId = androidInfo.id;
  } else if (Platform.isIOS) {
    IosDeviceInfo iosInfo = await deviceInfo.iosInfo;
    deviceId = iosInfo.identifierForVendor;
  }

**Comment by nohli** [comment]
Makes sense. This id is not unique.

Since you've posted this issue in the android_id package:
Are you looking for a unique id for Android? Please refer to the readme of this plugin 😊

But maybe just generating and storing a uuid per device would make more sense?

**Comment by telestia** [comment]
Thank you for your answer and your advice.
