### ISSUE TITLE
   > Could not get unknown property 'android' for project ':android_id' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by OE-Ahmed** [fluttercommunity/android_id#59]
![image](https://github.com/fluttercommunity/android_id/assets/88419792/147a201d-c118-4e7a-a3ad-74eccf15ccce)

**Comment by nohli** [comment]
Hi @OE-Ahmed, thanks for opening this issue!

Can you please do a `flutter clean`, then upgrade this plugin to the latest version, and build again - to see if there is a cache issue?

If it doesn't help, please provide the contents of your `android/build.gradle` and `android/app/build.gradle` (please no screenshot, but the code, each wrapped in ```).
